method: "Adam"
opt_params:
  lr: 3e-4
lr_scheduler: "CosineAnnealing"
batch_size: 4
epochs: 250
steps: -1
gamma_conc: 1.0
gamma_rate: 0.25
field_magnitude: 0.5
t_end: 15
integrator: "rk4"
step_size: 0.2